export const ERROR_CODE = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  STORE_NOT_FOUND: 'STORE_NOT_FOUND',
  STORE_NOT_APPROVED: 'STORE_NOT_APPROVED',
  STORE_ALREADY_EXISTS: 'STORE_ALREADY_EXISTS',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  PRODUCT_EXPIRED: 'PRODUCT_EXPIRED',
  ORDER_EXPIRED: 'ORDER_EXPIRED',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',
  PAYMENT_CONFIRM_FAILED: 'PAYMENT_CONFIRM_FAILED',
  PICKUP_NUMBER_EXHAUSTED: 'PICKUP_NUMBER_EXHAUSTED',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
